name: ci/gh-actions/build

on: [push, pull_request]

jobs:
  build-ubuntu-boost-1.71:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install morelo dependencies
      run: sudo apt -y install build-essential cmake graphviz doxygen libunwind8-dev pkg-config libssl-dev libsodium-dev libhidapi-dev libusb-1.0-0-dev gperf libreadline-dev
    - name: build and install boost 1.71
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.71.0/source/boost_1_71_0.tar.gz
        tar -xvf boost_1_71_0.tar.gz
        cd boost_1_71_0
        ./bootstrap.sh
        ./b2 -j4
        sudo ./b2 install
        sudo ./b2 headers
    - name: build
      run: make -j2
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: release-linux-boost-1.71
        path: |
            /home/runner/work/morelo/morelo/build/Linux/release/bin/morelo*

  build-ubuntu-boost-1.74:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install morelo dependencies
      run: sudo apt -y install build-essential cmake graphviz doxygen libunwind8-dev pkg-config libssl-dev libsodium-dev libhidapi-dev libusb-1.0-0-dev gperf libreadline-dev
    - name: build and install boost 1.74
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_74_0.tar.gz
        tar -xvf boost_1_74_0.tar.gz
        cd boost_1_74_0
        ./bootstrap.sh
        ./b2 -j4
        sudo ./b2 install
        sudo ./b2 headers
    - name: build
      run: make -j2
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: release-linux-boost-1.74
        path: |
            /home/runner/work/morelo/morelo/build/Linux/release/bin/morelo*
  
  build-ubuntu-boost-1.73:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install morelo dependencies
      run: sudo apt -y install build-essential cmake graphviz doxygen libunwind8-dev pkg-config libssl-dev libsodium-dev libhidapi-dev libusb-1.0-0-dev gperf libreadline-dev
    - name: build and install boost 1.73
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.tar.gz
        tar -xvf boost_1_73_0.tar.gz
        cd boost_1_73_0
        ./bootstrap.sh
        ./b2 -j4
        sudo ./b2 install
        sudo ./b2 headers
    - name: build
      run: make -j2
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: release-linux-boost-1.73
        path: |
            /home/runner/work/morelo/morelo/build/Linux/release/bin/morelo*

  build-ubuntu-boost-1.81:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install morelo dependencies
      run: sudo apt -y install build-essential cmake graphviz doxygen libunwind8-dev pkg-config libssl-dev libsodium-dev libhidapi-dev libusb-1.0-0-dev gperf libreadline-dev
    - name: build and install boost 1.81
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
        tar -xvf boost_1_81_0.tar.gz
        cd boost_1_81_0
        ./bootstrap.sh
        ./b2 -j4
        sudo ./b2 install
        sudo ./b2 headers
    - name: build
      run: make -j2
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: release-linux-boost-1.81
        path: |
            /home/runner/work/morelo/morelo/build/Linux/release/bin/morelo*
  