name: ci/gh-actions/build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  APT_INSTALL: 'sudo apt-get -y install build-essential cmake libboost-all-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libsodium-dev libhidapi-dev libusb-1.0-0-dev gperf libreadline-dev miniupnpc libunbound-dev libzmq3-dev libnorm-dev libpgm-dev libprotobuf-dev protobuf-compiler ccache libtool autotools-dev automake bsdmainutils curl git ca-certificates python3 qttools5-dev-tools'
  USE_DEVICE_TREZOR_MANDATORY: ON
  CCACHE_TEMPDIR: /tmp/.ccache-temp
  CCACHE_DIR: ~/.ccache
  CCACHE_SETTINGS: |
    ccache --max-size=150M
    ccache --set-config=compression=true

jobs:
  windows:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ runner.os }}-x86_64-w64-mingw32-${{ github.sha }}
        restore-keys: ccache-${{ runner.os }}-x86_64-w64-mingw32
    - name: depends ccache
      uses: actions/cache@v4
      with:
        path: contrib/depends/built
        key: ccache-depends-${{ runner.os }}-x86_64-w64-mingw32-${{ hashFiles('contrib/depends/packages/*') }}
        restore-keys: |
          ccache-depends-${{ runner.os }}-x86_64-w64-mingw32-${{ hashFiles('contrib/depends/packages/*') }}
          ccache-depends-${{ runner.os }}-x86_64-w64-mingw32
    - name: update apt
      run: sudo apt-get update
    - name: install dependencies
      run: ${{ env.APT_INSTALL }} g++-mingw-w64-x86-64 zip
    - name: prepare toolchain
      run: |
        sudo update-alternatives --set x86_64-w64-mingw32-g++ $(which x86_64-w64-mingw32-g++-posix)
        sudo update-alternatives --set x86_64-w64-mingw32-gcc $(which x86_64-w64-mingw32-gcc-posix)
    - name: build
      run: |
        ${{ env.CCACHE_SETTINGS }}
        make -j$(nproc) depends target=x86_64-w64-mingw32 buildtag=win-x64
    - name: package
      run: |
        cd ${{ github.workspace }}/build/release/bin
        zip -9 ../win-x64.zip morelo*
        cd ..
        mv win-x64.zip $(sha256sum win-x64.zip | cut -d " " -f 1).zip
    - uses: actions/upload-artifact@v4
      with:
        name: win-x64
        path: '${{ github.workspace }}/build/release/*.zip'
        compression-level: 0

  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04 ]
    env:
      BUILD_NAME: ${{ matrix.os == 'ubuntu-24.04' && 'ubuntu24' || 'ubuntu22' }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ runner.os }}-${{ matrix.os }}-${{ github.sha }}
        restore-keys: ccache-${{ runner.os }}-${{ matrix.os }}
    - name: update apt
      run: sudo apt-get update
    - name: install dependencies
      run: ${{ env.APT_INSTALL }}
    - name: build
      run: |
        ${{ env.CCACHE_SETTINGS }}
        make -j$(nproc) release-${{ env.BUILD_NAME }}
    - name: package
      run: |
        cd ${{ github.workspace }}/build/release/bin
        tar cJf ../linux-x64-${{ env.BUILD_NAME }}.tar.xz --owner=0 --group=0 morelo*
        cd ..
        mv linux-x64-${{ env.BUILD_NAME }}.tar.xz $(sha256sum linux-x64-${{ env.BUILD_NAME }}.tar.xz | cut -d " " -f 1).tar.xz
    - uses: actions/upload-artifact@v4
      with:
        name: linux-x64-${{ env.BUILD_NAME }}
        path: '${{ github.workspace }}/build/release/*.tar.xz'
        compression-level: 0
