name: ci/gh-actions/windows-build-test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  USE_DEVICE_TREZOR_MANDATORY: ON
  CCACHE_TEMPDIR: /tmp/.ccache-temp
  CCACHE_DIR: /tmp/.ccache
  CCACHE_SETTINGS: |
    ccache --max-size=150M
    ccache --set-config=compression=true

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-doxygen mingw-w64-x86_64-cmake mingw-w64-x86_64-ccache mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf mingw-w64-x86_64-libusb mingw-w64-x86_64-unbound mingw-w64-x86_64-graphviz git mingw-w64-x86_64-pkgconf mingw-w64-x86_64-ccache mingw-w64-x86_64-libunwind mingw-w64-x86_64-gperf mingw-w64-x86_64-miniupnpc mingw-w64-x86_64-zeromq mingw-w64-x86_64-cppzmq mingw-w64-x86_64-gpgme mingw-w64-x86_64-dlfcn
    - name: ccache
      uses: actions/cache@v4
      with:
        path: ${{ steps.msys2.outputs.msys2-location }}\tmp\.ccache
        key: ccache-${{ runner.os }}-msys2-${{ github.sha }}
        restore-keys: ccache-${{ runner.os }}-msys2
    - name: install boost
      run: |
        pacman --noconfirm -U contrib/mingw-w64-x86_64-boost-1.83.0-2-any.pkg.tar.zst
    - name: build
      run: |
        ${{ env.CCACHE_SETTINGS }}
        make -j$(nproc) release-static-win-x86_64
    - name: package
      run: |
        cd ${{ github.workspace }}/build/release/bin
        zip -9 ../win-x64.zip morelo*
        cd ..
        mv win-x64.zip $(sha256sum win-x64.zip | cut -d " " -f 1).zip
    - uses: actions/upload-artifact@v4
      with:
        name: win-x64
        path: '${{ github.workspace }}/build/release/*.zip'
        compression-level: 0
